<?php
declare(strict_types=1);
/**
 * CMS Manifest Generator
 * Usage: php tools/generate-manifest.php
 * Output: tools/cms-manifest.json (core file hashes for update system)
 * 
 * Scans the project and generates SHA256 hashes for all CMS core files.
 * Files matching PRESERVE patterns are EXCLUDED (not part of CMS core).
 */

$ROOT = dirname(__DIR__);

// Allow re-use from build-package.php (skip re-run if already defined)
if (!defined('GENERATE_MANIFEST_RUNNING')) {
    define('GENERATE_MANIFEST_RUNNING', true);
}

// Patterns that are SITE-SPECIFIC (preserved during update)
const PRESERVE_PATTERNS = [
    // Config
    '#^cfg/\.env$#',
    '#^cfg/var/#',
    '#^cfg/session_debug\.log$#',
    '#^cfg/php-noteloc\.ini$#',
    '#^cfg/\.env\.old$#',
    '#^cfg/env\.php$#',  // generated by installer

    // Git
    '#^\.git/#',
    '#^\.gitignore$#',
    '#^\.gitattributes$#',

    // Docs
    '#^AGENTS\.md$#',
    '#^README\.md$#',
    '#^INSTALL\.md$#',
    '#^SERVER_SETUP\.md$#',

    // Uploaded content
    '#^public/static/img/#',
    '#^public/static/files/#',
    '#^public/sitemaps/#',
    '#^private_files/#',

    // Themes (user-installed, keep during update)
    '#^public/views/themes/[^/]+$#',          // theme dirs
    '#^public/views/themes/[^/]+/.+#',        // theme files

    // Plugins
    '#^plugins/[^/]+/.+#',

    // Plugin-installed vendor assets
    '#^public/static/vendor/xterm/#',

    // Node modules
    '#node_modules/#',

    // Generated / runtime
    '#^tools/cms-manifest\.json$#',
    '#\.DS_Store$#',
    '#Thumbs\.db$#',

    // PWA files (adammuiz.com specific, preserved)
    '#^public/pdf/#',
];

function isPreserved(string $relative): bool {
    foreach (PRESERVE_PATTERNS as $pattern) {
        if (preg_match($pattern, $relative)) return true;
    }
    return false;
}

echo "Scanning {$ROOT}...\n";

$files = [];
$it = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($ROOT, RecursiveDirectoryIterator::SKIP_DOTS)
);

foreach ($it as $fileinfo) {
    $realPath = $fileinfo->getRealPath();
    if (!$realPath || !$fileinfo->isFile()) continue;

    $relative = substr($realPath, strlen($ROOT) + 1);

    // Skip preserved paths
    if (isPreserved($relative)) continue;

    // Only include certain top-level dirs (CMS core)
    $parts = explode('/', $relative, 2);
    $topDir = $parts[0];

    $allowedDirs = ['app', 'cfg', 'dashboard', 'public', 'schema', 'tools'];
    $allowedRootFiles = ['version.json', 'router.php', 'VERSION', '.gitattributes', 'LICENSE'];

    if (!in_array($topDir, $allowedDirs, true)) {
        continue; // Skip random root-level files
    }

    if ($topDir === $relative && !in_array($relative, $allowedRootFiles, true)) {
        continue; // Only allow specific root files
    }

    $hash = hash_file('sha256', $realPath);
    $files[$relative] = $hash;

    if (count($files) % 100 === 0) {
        echo "  ... {$relative}\n";
    }
}

ksort($files);

$version = json_decode(file_get_contents($ROOT . '/version.json'), true);
$manifest = [
    'name' => $version['name'] ?? 'Jyavani CMS',
    'version' => $version['version'] ?? '0.0.0',
    'build' => $version['build'] ?? date('Y-m-d'),
    'generated' => date('c'),
    'php_required' => $version['php_required'] ?? '8.1',
    'mysql_required' => $version['mysql_required'] ?? '5.7',
    'total_files' => count($files),
    'files' => $files,
];

$outPath = $ROOT . '/tools/cms-manifest.json';
file_put_contents($outPath, json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

echo "\nDone. {$manifest['total_files']} files hashed.\n";
echo "Manifest: {$outPath}\n";
echo "Size: " . number_format(filesize($outPath)) . " bytes\n";
