<?php
declare(strict_types=1);
/**
 * CMS Manifest Generator
 * Usage: php tools/generate-manifest.php
 * Output: tools/cms-manifest.json (core file hashes for update system)
 * 
 * Scans the project and generates SHA256 hashes for all CMS core files.
 * Files matching PRESERVE patterns are EXCLUDED (not part of CMS core).
 */

$ROOT = dirname(__DIR__);

// Allow re-use from build-package.php (skip re-run if already defined)
if (!defined('GENERATE_MANIFEST_RUNNING')) {
    define('GENERATE_MANIFEST_RUNNING', true);
}

// Patterns that are SITE-SPECIFIC (preserved during update)
const PRESERVE_PATTERNS = [
    // Config
    '#^cfg/\.env$#',
    '#^cfg/var/#',
    '#^cfg/session_debug\.log$#',
    '#^cfg/php-noteloc\.ini$#',
    '#^cfg/\.env\.old$#',
    '#^cfg/env\.php$#',  // generated by installer

    // Git
    '#^\.git/#',
    '#^\.gitignore$#',
    '#^\.gitattributes$#',

    // Docs
    '#^AGENTS\.md$#',
    '#^README\.md$#',
    '#^INSTALL\.md$#',
    '#^SERVER_SETUP\.md$#',

    // Uploaded content
    '#^public/static/img/#',
    '#^public/static/files/#',
    '#^public/sitemaps/#',
    '#^private_files/#',

    // Themes (user-installed, keep during update)
    '#^public/views/themes/[^/]+$#',          // theme dirs
    '#^public/views/themes/[^/]+/.+#',        // theme files

    // Plugins
    '#^plugins/[^/]+/.+#',
    '#^public/static/plugins/#',

    // Community/Store extensions maintained outside the Core package
    '#^app/controllers/DownloadController\.php$#',
    '#^dashboard/admin/community/#',
    '#^public/download/#',
    '#^public/static/community/#',
    '#^public/views/community/#',
    '#^public/views/member/#',
    '#^schema/community\.sql$#',
    '#^schema/migrations/008-dev-status-varchar\.sql$#',

    // Plugin-installed vendor assets
    '#^public/static/vendor/xterm/#',
    '#^public/static/vendor/jyavani-builder/#',
    '#^public/static/js/photo_canvas\.js$#',

    // Node modules
    '#node_modules/#',

    // Generated / runtime
    '#^tools/cms-manifest\.json$#',
    '#^var/#',
    '#\.DS_Store$#',
    '#Thumbs\.db$#',

    // PWA files (adammuiz.com specific, preserved)
    '#^public/pdf/#',
];

function isPreserved(string $relative): bool {
    foreach (PRESERVE_PATTERNS as $pattern) {
        if (preg_match($pattern, $relative)) return true;
    }
    return false;
}

function restorePluginStaticAssets(string $root): int {
    $restored = 0;
    $publicRoot = realpath($root . '/public');
    if ($publicRoot === false) return 0;

    foreach (glob($root . '/plugins/*/plugin.json') ?: [] as $manifestFile) {
        $pluginDir = dirname($manifestFile);
        $pluginName = basename($pluginDir);
        $manifest = json_decode((string)file_get_contents($manifestFile), true);
        if (!is_array($manifest) || ($manifest['name'] ?? '') !== $pluginName) continue;

        $staticCopy = $manifest['static']['copy'] ?? [];
        if (!is_array($staticCopy)) continue;
        foreach ($staticCopy as $entry) {
            $from = (string)($entry['from'] ?? '');
            $to = (string)($entry['to'] ?? '');
            $sourceParts = explode('/', $from);
            $targetParts = explode('/', $to);
            if ($from === '' || str_contains($from, "\0") || str_contains($from, '\\') || str_starts_with($from, '/')
                || str_contains($to, "\0") || str_contains($to, '\\') || str_starts_with($to, '/')
                || in_array('', $sourceParts, true) || in_array('.', $sourceParts, true) || in_array('..', $sourceParts, true)
                || in_array('', $targetParts, true) || in_array('.', $targetParts, true) || in_array('..', $targetParts, true)
                || !str_starts_with($to, 'static/plugins/' . $pluginName . '/')) {
                continue;
            }

            $source = realpath($pluginDir . '/' . $from);
            $pluginRoot = realpath($pluginDir);
            if ($source === false || $pluginRoot === false || !is_file($source) || is_link($source)
                || !str_starts_with($source, $pluginRoot . DIRECTORY_SEPARATOR)) {
                continue;
            }

            $destination = $publicRoot . '/' . $to;
            $destinationDir = dirname($destination);
            $existingParent = $destinationDir;
            while (!file_exists($existingParent) && dirname($existingParent) !== $existingParent) {
                $existingParent = dirname($existingParent);
            }
            $realExistingParent = realpath($existingParent);
            if ($realExistingParent === false || ($realExistingParent !== $publicRoot && !str_starts_with($realExistingParent, $publicRoot . DIRECTORY_SEPARATOR))) {
                continue;
            }
            if (!is_dir($destinationDir) && !mkdir($destinationDir, 0755, true)) continue;
            $realDestinationDir = realpath($destinationDir);
            if ($realDestinationDir === false || ($realDestinationDir !== $publicRoot && !str_starts_with($realDestinationDir, $publicRoot . DIRECTORY_SEPARATOR))
                || is_link($destination)) {
                continue;
            }
            if (!is_file($destination) || hash_file('sha256', $source) !== hash_file('sha256', $destination)) {
                if (copy($source, $destination)) $restored++;
            }
        }
    }
    return $restored;
}

$restoredPluginAssets = restorePluginStaticAssets($ROOT);
if ($restoredPluginAssets > 0) {
    echo "Restored {$restoredPluginAssets} plugin static assets.\n";
}

echo "Scanning {$ROOT}...\n";

$files = [];
$it = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($ROOT, RecursiveDirectoryIterator::SKIP_DOTS),
    RecursiveIteratorIterator::LEAVES_ONLY,
    RecursiveIteratorIterator::CATCH_GET_CHILD
);

foreach ($it as $fileinfo) {
    $realPath = $fileinfo->getRealPath();
    if (!$realPath || !$fileinfo->isFile()) continue;

    $relative = substr($realPath, strlen($ROOT) + 1);

    // Skip preserved paths
    if (isPreserved($relative)) continue;

    // Only include certain top-level dirs (CMS core)
    $parts = explode('/', $relative, 2);
    $topDir = $parts[0];

    $allowedDirs = ['app', 'cfg', 'dashboard', 'plugins', 'public', 'schema', 'tools'];
    $allowedRootFiles = ['version.json', 'router.php', 'VERSION', '.gitattributes', 'LICENSE'];

    if (!in_array($topDir, $allowedDirs, true)) {
        continue; // Skip random root-level files
    }

    if ($topDir === $relative && !in_array($relative, $allowedRootFiles, true)) {
        continue; // Only allow specific root files
    }

    $hash = hash_file('sha256', $realPath);
    $files[$relative] = $hash;

    if (count($files) % 100 === 0) {
        echo "  ... {$relative}\n";
    }
}

ksort($files);

$version = json_decode(file_get_contents($ROOT . '/version.json'), true);
$manifest = [
    'name' => $version['name'] ?? 'Jyavani CMS',
    'version' => $version['version'] ?? '0.0.0',
    'build' => $version['build'] ?? date('Y-m-d'),
    'generated' => date('c'),
    'edition' => $version['edition'] ?? '',
    'php_required' => $version['php_required'] ?? '8.1',
    'mysql_required' => $version['mysql_required'] ?? '5.7',
    'total_files' => count($files),
    'files' => $files,
];

$outPath = $ROOT . '/tools/cms-manifest.json';
if (file_put_contents($outPath, json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)) === false) {
    fwrite(STDERR, "ERROR: Cannot write manifest: {$outPath}\n");
    exit(1);
}

echo "\nDone. {$manifest['total_files']} files hashed.\n";
echo "Manifest: {$outPath}\n";
echo "Size: " . number_format(filesize($outPath)) . " bytes\n";
